### ISSUE TITLE
ntpd failure

### ISSUE THREAD

**Issue by reverendhomer** [troglobit/troglos#5]
Looks like ntpd service is broken by default. Every time I'm starting the troglos, I got these errors:
![img](http://i.imgur.com/o0Hzd2M.png)

so I have to type `initctl stop ntpd` blindly.

Can you reproduce this?

**Comment by troglobit** [comment]
Oy vey, sorry for not seeing this until now!  

Yes, there's been a long period of inactivity and only some commits that have introduced regressions. I'm finalizing some other projects atm, but when I'm integrating them, for testing, I'll look into this.

**Comment by troglobit** [comment]
Fixed in latest master.  No services enabled by default, have to be enabled explicitly
on target using `initctl enable <conf>`.

Still pending release of Finit 3.0 though, but with finit-dev (latest git) it works. So closing.

```sh
root@chaos:~ $ initctl show
#      STATUS   PID     RUNLEVELS   SERVICE               DESCRIPTION                                                                   
1      running  97      [S12345]    syslogd               System log daemon    
2      running  98      [S12345]    klogd                 Kernel log daemon    
root@chaos:~ $ initctl list
/etc/finit.d/available:
getty.conf      http.conf       inetd.conf      lldpd.conf      ntpd.conf       rdate.conf      snmpd.conf      sshd.conf       
telnetd.conf    uftpd.conf      watchdogd.conf  

/etc/finit.d:
getty.conf  

root@chaos:~ $ initctl enable ntpd
root@chaos:~ $ initctl reload
root@chaos:~ $ initctl status
#      STATUS   PID     RUNLEVELS   SERVICE               DESCRIPTION                                                                   
1      running  97      [S12345]    syslogd               System log daemon    
2      running  98      [S12345]    klogd                 Kernel log daemon    
3      running  136     [2345]      ntpd                  NTP client/server    
root@chaos:~ $ 
```
