### ISSUE TITLE
Options to set crosstool-ng version

### ISSUE THREAD

**Issue by seokbeomKim** [troglobit/troglos#8]
### Working Environment
- O/S: Arch Linux (4.19.56-1-lts x86_64 GNU/Linux)
- Toolchain: arm-unknown-linux-gnueabi (built with crosstool-ng-1.24.0-rc3)

When I follow the installation instruction, I got an following error message:
`

### Failure in `make`
```
CHECK   Toolchain version ... FAIL
FAIL    Wrong toolchain version, should be crosstool-ng-1.23.0-319-gaca85cb
make[1]: *** [Makefile:22: dep] Error 1
make: *** [Makefile:66: dep] Error 2
```
I've tried to set the version `TOOLCHAIN` flag in `core.mk:1` file, but it did not work at all. Is there any other options that I've missed for this issue?

**Comment by troglobit** [comment]
First of all, sorry for the laaaaaaate reply! The notification must have gotten lost when I went on vacation or something. 

It's definitely the `TOOLCHAIN` flag in `core.mk`.  The check looks there, but it's more or less required to be a [crosstool-NG](https://github.com/crosstool-ng/crosstool-ng/) based toolchain at the moment.   So we should probably get a menuconfig option to disable the check completely.
